---
services:
  tofu-workspace:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tofu-workspace
    volumes:
      - ..:/workspaces:cached
      - automation:/var/automation
    command: sleep infinity
volumes:
  automation:
    driver_opts:
      type: "nfs"
      o: "addr=172.16.60.2,vers=4,hard,timeo=600"
      device: ":/exports/automation"
